analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
config-version: 2
macro-paths:
- macros
model-paths:
- models
name: mxcp_template
profile: mxcp_template_default
seed-paths:
- seeds
snapshot-paths:
- snapshots
target-path: target
test-paths:
- tests
